FROM python:3.8-slim-buster

WORKDIR apps
COPY . . 

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN apt-get update && apt-get -y install libpq-dev gcc && \
    apt-get clean && pip install psycopg2

EXPOSE 8001

RUN pip install --upgrade pip
RUN pip install -r requirements.txt
